### ISSUE TITLE
Popup incompatible with left positioned dock

### ISSUE THREAD

**Issue by AnthonyMaiorani** [SoFriendly/2fhey#40]
If the dock position on screen is set to left, the 2FHey popup appears behind the dock, making it near impossible to see.

One idea for a solution for this would be to allow the user to pick which corner to use for the popup. Or possibly have some sort of indication through the menu bar icon rather than a pop-up.

**Comment by KaranErry** [comment]
I have this problem as well. @SoFriendly Is there any way to fix? Currently it's quite unhelpful to not know when the code has been received by 2FHey.

**Comment by itsthisjustin** [comment]
Ah gotcha. Let me see what I can do.

**Comment by jpminor** [comment]
I never even see the popup 2FH because it's behind an application or finder window most of the time.
However, 2FH is pretty darn reliable so it's more than likely that it's on the clipboard once you hear the sound or see the notification from Messages (assuming you have them on).  Just a take on why the 2FH popup isn't really that important to see - I'd even vote for an option of no popup at all.

**Comment by AnthonyMaiorani** [comment]
I don't have notification sounds for anything enabled and occasionally macOS decides it doesn't feel like displaying Messages.app notification banners. So I do usually watch for the 2FHey pop-up (the little of it I may be able to see behind the dock). 

I do think something as simple as the menu bar icon changing to a checkmark temporarily would suffice though. Just throwing out ideas.

**Comment by itsthisjustin** [comment]
Hey everyone, please test this updated installer before I send to all the users. In the dropdown in the menu bar you will find a notification position you can now select. https://files.sofriendly.com/uky23lc3
